# Generated by Django 5.2.5 on 2025-08-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=120)),
                ('edad', models.PositiveIntegerField()),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='oficinas.oficina')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
